[workspace]
members = [
    "tests",
    "libs/das-bloom-filter",
    "contracts/perf-analysis"
]

[profile.release]
overflow-checks = true
opt-level = 's'
lto = true
codegen-units = 1
panic = 'abort'
